### ISSUE TITLE
Signature or access key missing

### ISSUE THREAD

**Issue by aharris02** [cvondrick/turkic#3]
Hi - I'm seeing the following when I try to publish:

```
Traceback (most recent call last):
  File "/usr/local/bin/turkic", line 5, in <module>
    pkg_resources.run_script('turkic==0.2.5', 'turkic')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/EGG-INFO/scripts/turkic", line 16, in <module>
    turkic.cli.main()
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/cli.py", line 147, in main
    handler(args[1:])
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/cli.py", line 47, in __init__
    self(parser.parse_args(args))
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/cli.py", line 325, in __call__
    hit.publish()
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/models.py", line 131, in publish
    page = self.getpage())
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/api.py", line 112, in createhit
    r = self.request("CreateHIT", r);
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/api.py", line 32, in request
    raise RuntimeError("Signature or access key missing")
RuntimeError: Signature or access key missing

```

Not sure where to turn with this one. Any ideas what would cause this?

**Comment by aharris02** [comment]
Answered my own question. No ATurk credentials because I'm attempting to publish offline; my command was missing the --offline flag. Thanks!
